name: Terraform Deployment

on:
  push:
    branches:
      - master  # Auto-trigger on push to master
  pull_request:
    branches:
      - master  # Runs Terraform Plan on PR
  workflow_dispatch:  # Allows manual trigger
    inputs:
      action:
        description: 'Choose action (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply (Manual Trigger)
        if: github.event_name == 'workflow_dispatch' && inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy (Manual Trigger)
        if: github.event_name == 'workflow_dispatch' && inputs.action == 'destroy'
        run: terraform destroy -auto-approve
